[package]
name = "day_1"
version = "0.1.0"
edition = "2021"

[lib]
name = "day_1"
path = "src/day_1.rs"

[[bin]]
name = "day_1_part_1"
path = "src/part_1.rs"
dependencies = [
    "day_1",
]

[[bin]]
name = "day_1_part_2"
path = "src/part_2.rs"
dependencies = [
    "day_1",
]

[dependencies]
